name: "[DEV] Build and Publish Android"
on: 
    push:
        branches:
            - main
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out our repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # Install flutter
      - name: Flutter get
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'

      # Install your project's dependencies
      - run: flutter pub get

      # Build and sign the ipa using a single flutter command
      - name: Building APK
        run: flutter build apk
          
      # Collect the file and upload as artifact         
      - name: collect apk artifacts
        uses: actions/upload-artifact@v2
        with:
         name: release-apk
         # Path to the release files
         path: build/app/outputs/flutter-apk/app-release.apk

  release:
    name: Release apk to AppCenter
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    
    # Retrieve ipa file from GitHub artifacts
    - uses: actions/checkout@v2
    - name: Get release-apk from artifacts
      uses: actions/download-artifact@v2
      with:
        name: release-apk
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: nangarita/Deploy-Test-Android
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: PE Internal Testing
        file: app-release.apk
        notifyTesters: true
        debug: false
